// Chip Tuning Araç Veritabanı - GM Opel ve Chevrolet
export interface EngineVariant {
  name: string;
  displacement: string;
  fuelType: "Dizel" | "Benzin";
  originalHP: number;
  originalTorque: number;
  stage1HP: number;
  stage1Torque: number;
  stage2HP?: number;
  stage2Torque?: number;
  stage3HP?: number;
  stage3Torque?: number;
}

export interface CarModel {
  name: string;
  years: string[];
  engines: EngineVariant[];
}

export interface CarBrand {
  name: string;
  logo?: string;
  models: CarModel[];
}

export const chipTuningData: CarBrand[] = [
  {
    name: "Opel",
    models: [
      {
        name: "Astra H",
        years: ["2004", "2005", "2006", "2007", "2008", "2009", "2010"],
        engines: [
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 90,
            originalTorque: 200,
            stage1HP: 115,
            stage1Torque: 250,
            stage2HP: 130,
            stage2Torque: 280,
          },
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 100,
            originalTorque: 240,
            stage1HP: 130,
            stage1Torque: 300,
            stage2HP: 150,
            stage2Torque: 340,
          },
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 260,
            stage1HP: 140,
            stage1Torque: 320,
            stage2HP: 160,
            stage2Torque: 360,
          },
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 125,
            originalTorque: 280,
            stage1HP: 155,
            stage1Torque: 340,
            stage2HP: 175,
            stage2Torque: 380,
          },
          {
            name: "1.9 CDTI",
            displacement: "1910cc",
            fuelType: "Dizel",
            originalHP: 120,
            originalTorque: 280,
            stage1HP: 150,
            stage1Torque: 340,
            stage2HP: 175,
            stage2Torque: 380,
          },
          {
            name: "1.9 CDTI",
            displacement: "1910cc",
            fuelType: "Dizel",
            originalHP: 150,
            originalTorque: 320,
            stage1HP: 185,
            stage1Torque: 400,
            stage2HP: 210,
            stage2Torque: 440,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 200,
            stage1HP: 170,
            stage1Torque: 250,
            stage2HP: 190,
            stage2Torque: 280,
          },
          {
            name: "2.0 Turbo",
            displacement: "1998cc",
            fuelType: "Benzin",
            originalHP: 170,
            originalTorque: 250,
            stage1HP: 210,
            stage1Torque: 310,
            stage2HP: 240,
            stage2Torque: 350,
          },
          {
            name: "2.0 Turbo OPC",
            displacement: "1998cc",
            fuelType: "Benzin",
            originalHP: 240,
            originalTorque: 320,
            stage1HP: 280,
            stage1Torque: 400,
            stage2HP: 310,
            stage2Torque: 440,
            stage3HP: 350,
            stage3Torque: 480,
          },
        ],
      },
      {
        name: "Astra J",
        years: ["2009", "2010", "2011", "2012", "2013", "2014", "2015"],
        engines: [
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 95,
            originalTorque: 190,
            stage1HP: 120,
            stage1Torque: 240,
            stage2HP: 140,
            stage2Torque: 280,
          },
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 260,
            stage1HP: 140,
            stage1Torque: 320,
            stage2HP: 160,
            stage2Torque: 360,
          },
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 125,
            originalTorque: 280,
            stage1HP: 155,
            stage1Torque: 340,
            stage2HP: 175,
            stage2Torque: 380,
          },
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 130,
            originalTorque: 300,
            stage1HP: 160,
            stage1Torque: 360,
            stage2HP: 180,
            stage2Torque: 400,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 160,
            originalTorque: 350,
            stage1HP: 195,
            stage1Torque: 420,
            stage2HP: 220,
            stage2Torque: 460,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 165,
            originalTorque: 380,
            stage1HP: 200,
            stage1Torque: 450,
            stage2HP: 225,
            stage2Torque: 490,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 120,
            originalTorque: 175,
            stage1HP: 150,
            stage1Torque: 225,
            stage2HP: 170,
            stage2Torque: 260,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 200,
            stage1HP: 170,
            stage1Torque: 255,
            stage2HP: 190,
            stage2Torque: 290,
          },
          {
            name: "1.6 Turbo",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 180,
            originalTorque: 230,
            stage1HP: 215,
            stage1Torque: 290,
            stage2HP: 240,
            stage2Torque: 330,
          },
          {
            name: "2.0 Turbo OPC",
            displacement: "1998cc",
            fuelType: "Benzin",
            originalHP: 280,
            originalTorque: 400,
            stage1HP: 320,
            stage1Torque: 480,
            stage2HP: 360,
            stage2Torque: 520,
            stage3HP: 400,
            stage3Torque: 560,
          },
        ],
      },
      {
        name: "Astra K",
        years: ["2015", "2016", "2017", "2018", "2019", "2020", "2021"],
        engines: [
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 300,
            stage1HP: 140,
            stage1Torque: 360,
            stage2HP: 160,
            stage2Torque: 400,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 136,
            originalTorque: 320,
            stage1HP: 165,
            stage1Torque: 390,
            stage2HP: 185,
            stage2Torque: 430,
          },
          {
            name: "1.6 CDTI BiTurbo",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 160,
            originalTorque: 350,
            stage1HP: 195,
            stage1Torque: 420,
            stage2HP: 220,
            stage2Torque: 460,
          },
          {
            name: "1.0 Turbo",
            displacement: "999cc",
            fuelType: "Benzin",
            originalHP: 105,
            originalTorque: 170,
            stage1HP: 125,
            stage1Torque: 210,
          },
          {
            name: "1.4 Turbo",
            displacement: "1399cc",
            fuelType: "Benzin",
            originalHP: 125,
            originalTorque: 200,
            stage1HP: 155,
            stage1Torque: 255,
            stage2HP: 175,
            stage2Torque: 290,
          },
          {
            name: "1.4 Turbo",
            displacement: "1399cc",
            fuelType: "Benzin",
            originalHP: 150,
            originalTorque: 245,
            stage1HP: 180,
            stage1Torque: 300,
            stage2HP: 200,
            stage2Torque: 340,
          },
          {
            name: "1.6 Turbo",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 200,
            originalTorque: 300,
            stage1HP: 240,
            stage1Torque: 370,
            stage2HP: 270,
            stage2Torque: 410,
          },
        ],
      },
      {
        name: "Corsa D",
        years: ["2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014"],
        engines: [
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 75,
            originalTorque: 170,
            stage1HP: 95,
            stage1Torque: 210,
            stage2HP: 110,
            stage2Torque: 240,
          },
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 90,
            originalTorque: 190,
            stage1HP: 115,
            stage1Torque: 240,
            stage2HP: 130,
            stage2Torque: 270,
          },
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 95,
            originalTorque: 200,
            stage1HP: 120,
            stage1Torque: 250,
            stage2HP: 135,
            stage2Torque: 280,
          },
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 125,
            originalTorque: 280,
            stage1HP: 155,
            stage1Torque: 340,
            stage2HP: 175,
            stage2Torque: 380,
          },
          {
            name: "1.2 Twinport",
            displacement: "1229cc",
            fuelType: "Benzin",
            originalHP: 80,
            originalTorque: 110,
            stage1HP: 92,
            stage1Torque: 125,
          },
          {
            name: "1.4 Twinport",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 90,
            originalTorque: 125,
            stage1HP: 100,
            stage1Torque: 140,
          },
          {
            name: "1.6 Turbo OPC",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 192,
            originalTorque: 230,
            stage1HP: 225,
            stage1Torque: 290,
            stage2HP: 250,
            stage2Torque: 320,
          },
          {
            name: "1.6 Turbo OPC Nürburgring",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 210,
            originalTorque: 250,
            stage1HP: 240,
            stage1Torque: 310,
            stage2HP: 265,
            stage2Torque: 350,
          },
        ],
      },
      {
        name: "Corsa E",
        years: ["2014", "2015", "2016", "2017", "2018", "2019"],
        engines: [
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 75,
            originalTorque: 190,
            stage1HP: 95,
            stage1Torque: 230,
            stage2HP: 110,
            stage2Torque: 260,
          },
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 95,
            originalTorque: 220,
            stage1HP: 120,
            stage1Torque: 270,
            stage2HP: 135,
            stage2Torque: 300,
          },
          {
            name: "1.0 Turbo",
            displacement: "999cc",
            fuelType: "Benzin",
            originalHP: 90,
            originalTorque: 152,
            stage1HP: 110,
            stage1Torque: 190,
          },
          {
            name: "1.0 Turbo",
            displacement: "999cc",
            fuelType: "Benzin",
            originalHP: 115,
            originalTorque: 170,
            stage1HP: 135,
            stage1Torque: 210,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 100,
            originalTorque: 166,
            stage1HP: 125,
            stage1Torque: 210,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 150,
            originalTorque: 220,
            stage1HP: 180,
            stage1Torque: 275,
            stage2HP: 200,
            stage2Torque: 310,
          },
          {
            name: "1.6 Turbo OPC",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 207,
            originalTorque: 245,
            stage1HP: 240,
            stage1Torque: 310,
            stage2HP: 265,
            stage2Torque: 350,
          },
        ],
      },
      {
        name: "Insignia A",
        years: ["2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017"],
        engines: [
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 260,
            stage1HP: 140,
            stage1Torque: 320,
            stage2HP: 160,
            stage2Torque: 360,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 130,
            originalTorque: 300,
            stage1HP: 165,
            stage1Torque: 370,
            stage2HP: 185,
            stage2Torque: 410,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 160,
            originalTorque: 350,
            stage1HP: 195,
            stage1Torque: 420,
            stage2HP: 220,
            stage2Torque: 460,
          },
          {
            name: "2.0 CDTI BiTurbo",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 195,
            originalTorque: 400,
            stage1HP: 235,
            stage1Torque: 480,
            stage2HP: 260,
            stage2Torque: 520,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 200,
            stage1HP: 170,
            stage1Torque: 255,
            stage2HP: 190,
            stage2Torque: 290,
          },
          {
            name: "1.6 Turbo",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 170,
            originalTorque: 260,
            stage1HP: 205,
            stage1Torque: 320,
            stage2HP: 230,
            stage2Torque: 360,
          },
          {
            name: "2.0 Turbo",
            displacement: "1998cc",
            fuelType: "Benzin",
            originalHP: 220,
            originalTorque: 350,
            stage1HP: 265,
            stage1Torque: 430,
            stage2HP: 300,
            stage2Torque: 480,
          },
          {
            name: "2.8 V6 Turbo OPC",
            displacement: "2792cc",
            fuelType: "Benzin",
            originalHP: 325,
            originalTorque: 435,
            stage1HP: 380,
            stage1Torque: 530,
            stage2HP: 420,
            stage2Torque: 580,
            stage3HP: 470,
            stage3Torque: 640,
          },
        ],
      },
      {
        name: "Insignia B",
        years: ["2017", "2018", "2019", "2020", "2021", "2022"],
        engines: [
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 300,
            stage1HP: 140,
            stage1Torque: 360,
            stage2HP: 160,
            stage2Torque: 400,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 136,
            originalTorque: 320,
            stage1HP: 165,
            stage1Torque: 390,
            stage2HP: 185,
            stage2Torque: 430,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 170,
            originalTorque: 400,
            stage1HP: 210,
            stage1Torque: 480,
            stage2HP: 235,
            stage2Torque: 520,
          },
          {
            name: "2.0 CDTI BiTurbo",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 210,
            originalTorque: 480,
            stage1HP: 250,
            stage1Torque: 560,
            stage2HP: 280,
            stage2Torque: 610,
          },
          {
            name: "1.5 Turbo",
            displacement: "1490cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 250,
            stage1HP: 170,
            stage1Torque: 310,
          },
          {
            name: "1.5 Turbo",
            displacement: "1490cc",
            fuelType: "Benzin",
            originalHP: 165,
            originalTorque: 250,
            stage1HP: 195,
            stage1Torque: 310,
          },
          {
            name: "2.0 Turbo",
            displacement: "1998cc",
            fuelType: "Benzin",
            originalHP: 260,
            originalTorque: 400,
            stage1HP: 310,
            stage1Torque: 480,
            stage2HP: 350,
            stage2Torque: 530,
          },
          {
            name: "2.0 Turbo GSi",
            displacement: "1998cc",
            fuelType: "Benzin",
            originalHP: 260,
            originalTorque: 400,
            stage1HP: 310,
            stage1Torque: 490,
            stage2HP: 350,
            stage2Torque: 540,
            stage3HP: 400,
            stage3Torque: 590,
          },
        ],
      },
      {
        name: "Mokka",
        years: ["2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019"],
        engines: [
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 300,
            stage1HP: 140,
            stage1Torque: 360,
            stage2HP: 160,
            stage2Torque: 400,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 136,
            originalTorque: 320,
            stage1HP: 165,
            stage1Torque: 390,
            stage2HP: 185,
            stage2Torque: 430,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 200,
            stage1HP: 170,
            stage1Torque: 255,
            stage2HP: 190,
            stage2Torque: 290,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 152,
            originalTorque: 245,
            stage1HP: 185,
            stage1Torque: 300,
            stage2HP: 205,
            stage2Torque: 340,
          },
        ],
      },
      {
        name: "Zafira B",
        years: ["2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014"],
        engines: [
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 260,
            stage1HP: 140,
            stage1Torque: 320,
            stage2HP: 160,
            stage2Torque: 360,
          },
          {
            name: "1.7 CDTI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 125,
            originalTorque: 280,
            stage1HP: 155,
            stage1Torque: 340,
            stage2HP: 175,
            stage2Torque: 380,
          },
          {
            name: "1.9 CDTI",
            displacement: "1910cc",
            fuelType: "Dizel",
            originalHP: 120,
            originalTorque: 280,
            stage1HP: 150,
            stage1Torque: 340,
            stage2HP: 175,
            stage2Torque: 380,
          },
          {
            name: "1.9 CDTI",
            displacement: "1910cc",
            fuelType: "Dizel",
            originalHP: 150,
            originalTorque: 320,
            stage1HP: 185,
            stage1Torque: 400,
            stage2HP: 210,
            stage2Torque: 440,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 165,
            originalTorque: 380,
            stage1HP: 200,
            stage1Torque: 450,
            stage2HP: 225,
            stage2Torque: 490,
          },
          {
            name: "1.8 Ecotec",
            displacement: "1796cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 175,
            stage1HP: 155,
            stage1Torque: 195,
          },
          {
            name: "2.0 Turbo OPC",
            displacement: "1998cc",
            fuelType: "Benzin",
            originalHP: 240,
            originalTorque: 320,
            stage1HP: 280,
            stage1Torque: 400,
            stage2HP: 310,
            stage2Torque: 440,
            stage3HP: 350,
            stage3Torque: 480,
          },
        ],
      },
      {
        name: "Zafira C Tourer",
        years: ["2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019"],
        engines: [
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 120,
            originalTorque: 320,
            stage1HP: 150,
            stage1Torque: 390,
            stage2HP: 170,
            stage2Torque: 430,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 134,
            originalTorque: 320,
            stage1HP: 165,
            stage1Torque: 390,
            stage2HP: 185,
            stage2Torque: 430,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 130,
            originalTorque: 300,
            stage1HP: 165,
            stage1Torque: 370,
            stage2HP: 185,
            stage2Torque: 410,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 165,
            originalTorque: 380,
            stage1HP: 200,
            stage1Torque: 450,
            stage2HP: 225,
            stage2Torque: 490,
          },
          {
            name: "2.0 CDTI BiTurbo",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 195,
            originalTorque: 400,
            stage1HP: 235,
            stage1Torque: 480,
            stage2HP: 260,
            stage2Torque: 520,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 120,
            originalTorque: 175,
            stage1HP: 150,
            stage1Torque: 225,
            stage2HP: 170,
            stage2Torque: 260,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 200,
            stage1HP: 170,
            stage1Torque: 255,
            stage2HP: 190,
            stage2Torque: 290,
          },
          {
            name: "1.6 Turbo",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 170,
            originalTorque: 280,
            stage1HP: 205,
            stage1Torque: 340,
            stage2HP: 230,
            stage2Torque: 380,
          },
          {
            name: "1.6 Turbo",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 200,
            originalTorque: 300,
            stage1HP: 240,
            stage1Torque: 370,
            stage2HP: 270,
            stage2Torque: 410,
          },
        ],
      },
      {
        name: "Meriva B",
        years: ["2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017"],
        engines: [
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 75,
            originalTorque: 190,
            stage1HP: 95,
            stage1Torque: 230,
          },
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 95,
            originalTorque: 190,
            stage1HP: 120,
            stage1Torque: 240,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 95,
            originalTorque: 280,
            stage1HP: 125,
            stage1Torque: 340,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 300,
            stage1HP: 140,
            stage1Torque: 360,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 120,
            originalTorque: 175,
            stage1HP: 150,
            stage1Torque: 225,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 200,
            stage1HP: 170,
            stage1Torque: 255,
          },
        ],
      },
      {
        name: "Combo D",
        years: ["2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018"],
        engines: [
          {
            name: "1.3 CDTI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 90,
            originalTorque: 200,
            stage1HP: 115,
            stage1Torque: 250,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 90,
            originalTorque: 290,
            stage1HP: 120,
            stage1Torque: 350,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 105,
            originalTorque: 280,
            stage1HP: 135,
            stage1Torque: 340,
          },
          {
            name: "2.0 CDTI",
            displacement: "1956cc",
            fuelType: "Dizel",
            originalHP: 135,
            originalTorque: 320,
            stage1HP: 170,
            stage1Torque: 400,
          },
        ],
      },
      {
        name: "Vivaro B",
        years: ["2014", "2015", "2016", "2017", "2018", "2019"],
        engines: [
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 90,
            originalTorque: 260,
            stage1HP: 120,
            stage1Torque: 320,
          },
          {
            name: "1.6 CDTI",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 115,
            originalTorque: 300,
            stage1HP: 145,
            stage1Torque: 360,
          },
          {
            name: "1.6 CDTI BiTurbo",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 120,
            originalTorque: 320,
            stage1HP: 150,
            stage1Torque: 380,
          },
          {
            name: "1.6 CDTI BiTurbo",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 140,
            originalTorque: 340,
            stage1HP: 175,
            stage1Torque: 410,
          },
          {
            name: "1.6 CDTI BiTurbo",
            displacement: "1598cc",
            fuelType: "Dizel",
            originalHP: 145,
            originalTorque: 340,
            stage1HP: 180,
            stage1Torque: 410,
          },
        ],
      },
    ],
  },
  {
    name: "Chevrolet",
    models: [
      {
        name: "Cruze",
        years: ["2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016"],
        engines: [
          {
            name: "1.6",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 113,
            originalTorque: 150,
            stage1HP: 125,
            stage1Torque: 170,
          },
          {
            name: "1.8",
            displacement: "1796cc",
            fuelType: "Benzin",
            originalHP: 141,
            originalTorque: 177,
            stage1HP: 155,
            stage1Torque: 195,
          },
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 200,
            stage1HP: 170,
            stage1Torque: 255,
            stage2HP: 190,
            stage2Torque: 290,
          },
          {
            name: "2.0 VCDI",
            displacement: "1998cc",
            fuelType: "Dizel",
            originalHP: 150,
            originalTorque: 320,
            stage1HP: 185,
            stage1Torque: 400,
            stage2HP: 210,
            stage2Torque: 440,
          },
          {
            name: "2.0 VCDI",
            displacement: "1998cc",
            fuelType: "Dizel",
            originalHP: 163,
            originalTorque: 360,
            stage1HP: 200,
            stage1Torque: 440,
            stage2HP: 225,
            stage2Torque: 480,
          },
        ],
      },
      {
        name: "Aveo",
        years: ["2011", "2012", "2013", "2014", "2015"],
        engines: [
          {
            name: "1.2",
            displacement: "1206cc",
            fuelType: "Benzin",
            originalHP: 70,
            originalTorque: 95,
            stage1HP: 78,
            stage1Torque: 105,
          },
          {
            name: "1.2",
            displacement: "1206cc",
            fuelType: "Benzin",
            originalHP: 86,
            originalTorque: 115,
            stage1HP: 95,
            stage1Torque: 128,
          },
          {
            name: "1.4",
            displacement: "1399cc",
            fuelType: "Benzin",
            originalHP: 100,
            originalTorque: 130,
            stage1HP: 112,
            stage1Torque: 145,
          },
          {
            name: "1.3 VCDI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 75,
            originalTorque: 190,
            stage1HP: 95,
            stage1Torque: 230,
          },
          {
            name: "1.3 VCDI",
            displacement: "1248cc",
            fuelType: "Dizel",
            originalHP: 95,
            originalTorque: 210,
            stage1HP: 120,
            stage1Torque: 260,
          },
        ],
      },
      {
        name: "Captiva",
        years: ["2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015"],
        engines: [
          {
            name: "2.0 VCDI",
            displacement: "1991cc",
            fuelType: "Dizel",
            originalHP: 150,
            originalTorque: 320,
            stage1HP: 185,
            stage1Torque: 400,
            stage2HP: 210,
            stage2Torque: 440,
          },
          {
            name: "2.2 VCDI",
            displacement: "2231cc",
            fuelType: "Dizel",
            originalHP: 163,
            originalTorque: 350,
            stage1HP: 200,
            stage1Torque: 430,
            stage2HP: 225,
            stage2Torque: 470,
          },
          {
            name: "2.2 VCDI",
            displacement: "2231cc",
            fuelType: "Dizel",
            originalHP: 184,
            originalTorque: 400,
            stage1HP: 220,
            stage1Torque: 480,
            stage2HP: 245,
            stage2Torque: 520,
          },
          {
            name: "2.4",
            displacement: "2405cc",
            fuelType: "Benzin",
            originalHP: 136,
            originalTorque: 220,
            stage1HP: 150,
            stage1Torque: 245,
          },
          {
            name: "3.0 V6",
            displacement: "2997cc",
            fuelType: "Benzin",
            originalHP: 258,
            originalTorque: 288,
            stage1HP: 280,
            stage1Torque: 315,
          },
        ],
      },
      {
        name: "Orlando",
        years: ["2011", "2012", "2013", "2014", "2015"],
        engines: [
          {
            name: "1.8",
            displacement: "1796cc",
            fuelType: "Benzin",
            originalHP: 141,
            originalTorque: 177,
            stage1HP: 155,
            stage1Torque: 195,
          },
          {
            name: "2.0 VCDI",
            displacement: "1998cc",
            fuelType: "Dizel",
            originalHP: 130,
            originalTorque: 300,
            stage1HP: 165,
            stage1Torque: 370,
            stage2HP: 185,
            stage2Torque: 410,
          },
          {
            name: "2.0 VCDI",
            displacement: "1998cc",
            fuelType: "Dizel",
            originalHP: 163,
            originalTorque: 360,
            stage1HP: 200,
            stage1Torque: 440,
            stage2HP: 225,
            stage2Torque: 480,
          },
        ],
      },
      {
        name: "Trax",
        years: ["2013", "2014", "2015", "2016", "2017"],
        engines: [
          {
            name: "1.4 Turbo",
            displacement: "1364cc",
            fuelType: "Benzin",
            originalHP: 140,
            originalTorque: 200,
            stage1HP: 170,
            stage1Torque: 255,
            stage2HP: 190,
            stage2Torque: 290,
          },
          {
            name: "1.6",
            displacement: "1598cc",
            fuelType: "Benzin",
            originalHP: 115,
            originalTorque: 155,
            stage1HP: 128,
            stage1Torque: 170,
          },
          {
            name: "1.7 VCDI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 110,
            originalTorque: 260,
            stage1HP: 140,
            stage1Torque: 320,
            stage2HP: 160,
            stage2Torque: 360,
          },
          {
            name: "1.7 VCDI",
            displacement: "1686cc",
            fuelType: "Dizel",
            originalHP: 130,
            originalTorque: 300,
            stage1HP: 160,
            stage1Torque: 360,
            stage2HP: 180,
            stage2Torque: 400,
          },
        ],
      },
      {
        name: "Spark",
        years: ["2010", "2011", "2012", "2013", "2014", "2015"],
        engines: [
          {
            name: "1.0",
            displacement: "995cc",
            fuelType: "Benzin",
            originalHP: 68,
            originalTorque: 90,
            stage1HP: 75,
            stage1Torque: 100,
          },
          {
            name: "1.2",
            displacement: "1206cc",
            fuelType: "Benzin",
            originalHP: 81,
            originalTorque: 111,
            stage1HP: 90,
            stage1Torque: 125,
          },
        ],
      },
    ],
  },
];

// Stage açıklamaları
export const stageDescriptions = {
  stage1: {
    title: "Stage 1",
    description: "ECU yazılım optimizasyonu ile motor parametrelerinin ince ayarı. Herhangi bir donanım değişikliği gerektirmez.",
    benefits: [
      "Motor garantisi korunur",
      "Yakıt tasarrufu sağlar",
      "Geri alınabilir işlem",
      "Günlük kullanım için ideal",
    ],
    color: "from-green-500 to-emerald-600",
    bgColor: "bg-green-500/10",
    borderColor: "border-green-500/30",
    textColor: "text-green-400",
  },
  stage2: {
    title: "Stage 2",
    description: "Stage 1 + performans egzoz, yüksek akışlı hava filtresi ve güçlendirilmiş intercooler ile birlikte uygulanır.",
    benefits: [
      "Daha yüksek güç artışı",
      "Egzoz sistemi upgrade",
      "Hava filtresi modifikasyonu",
      "Intercooler upgrade",
    ],
    color: "from-amber-500 to-orange-600",
    bgColor: "bg-amber-500/10",
    borderColor: "border-amber-500/30",
    textColor: "text-amber-400",
  },
  stage3: {
    title: "Stage 3",
    description: "Maksimum performans için turbo upgrade, büyük turbo, yüksek basınç yakıt pompası ve güçlendirilmiş şanzıman gerektirir.",
    benefits: [
      "Maksimum güç artışı",
      "Turbo upgrade",
      "Yakıt sistemi upgrade",
      "Profesyonel yarış performansı",
    ],
    color: "from-red-500 to-rose-600",
    bgColor: "bg-red-500/10",
    borderColor: "border-red-500/30",
    textColor: "text-red-400",
  },
};
